### ISSUE TITLE
Barbarian assault plugin

### ISSUE THREAD

**Issue by twelve123322** [losingticks/plugin-releases#1]
Plugin request..
A barbarian assault plugin that works like the ba plugin from openosrs.
Features like:
- Removing unused menus.
- Removing incorrect calls.
- Highlighting bait/food/arrows.
etc..
As the standard ba plugin on runelite is terrible.

**Comment by losingticks** [comment]
i can definitely do this after i finish making a plugin hub, just need some time to work on it!
